### ISSUE TITLE
Rethink error handling

### ISSUE THREAD

**Issue by nhatbui** [nhatbui/captionbot#3]
Currently, all errors are panic'd. Improve the behavior to be more robust.

**Comment by brenol** [comment]
Probably Dave Cheney's https://github.com/pkg/errors should be used as it {is|seems} to be the standard way to handle errors in Go.

I can work on this (if using a external dependency is no problem for you)

**Comment by nhatbui** [comment]
@brenol Definitely would appreciate the contribution. External dependency is not a problem.

**Comment by brenol** [comment]
Noticed @kai5263499 has opened a PR for this issue. I will work on some other stuff based on his PR as it looks good IMO. What do you think?

**Comment by nhatbui** [comment]
@brenol really appreciate the feedback and would be grateful if you could continue to contribute. I did make a comment on #4 and would be interested in what you think. Thanks!

**Comment by brenol** [comment]
I agree! Was doing just that on the small PR I am going to open though.

**Comment by kai5263499** [comment]
Oh hey @brenol sorry if I stepped on your toes. I saw the issue come up on the Hacktoberfest feed earlier and thought I could knock it out real quick

**Comment by brenol** [comment]
@kai5263499  no problem! Was working on some other stuff as well on this project so no problem!

**Comment by nhatbui** [comment]
Updated by #4 . Thank you!
