### ISSUE TITLE
Example in README doesn't compile

### ISSUE THREAD

**Issue by nhatbui** [nhatbui/captionbot#5]
Track down and update the example in the README. It currently does not compile.

**Comment by billglover** [comment]
Current version of the README compiles and runs for me. Mac OSX 10.13, Go 1.9. However there is a an issue with the README example in that the errors never print out to the console. I'm happy to address these and submit a PR.

**Comment by nhatbui** [comment]
I incorrectly copy and pasted code locally and hastily made the issue. You're right, there's no issue but I definitely would appreciate any contribution you may have!

**Comment by billglover** [comment]
Ok, I'll get something over to you today.
