### ISSUE TITLE
Errors in the README example are never printed to the console

### ISSUE THREAD

**Issue by billglover** [nhatbui/captionbot#7]
Expected output:
```
I think it's a statue of a man
and he seems 😁.
error uploading caption stat /path/to/image.jpg: no such file or directory
exit status 255
```

Actual output:
```
I think it's a statue of a man
and he seems 😁.
exit status 255
```

In the current example, the error messages are never printed to the console and so remain invisible to the user. The only indication the user gets that something went wrong is the non-zero return code.

**Comment by nhatbui** [comment]
Fixed by #8
